development:
  adapter: postgresql
  database: sample_32_dev
  pool: 5
  timeout: 5000
  host: localhost
  username: mc
  password:

production:
  adapter: postgresql
  database: sample_32_prod
  pool: 5
  timeout: 5000
  host: localhost
  username: mc
  password: uni6mmx35
